language: python
python:
  - "3.7.4"  # 3.7 development branch
env:
  - DJANGO_VERSION=2.2.6

  - DJANGO_SETTINGS_MODULE='bankproject.settings.test' 
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test